header:
  version: 12

repos:
  poky:
    url: https://git.yoctoproject.org/git/poky
    refspec: 54af8c5e80ebf63707ef4e51cc9d374f716da603
    path: layers/poky
    layers:
      meta:
      meta-poky:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    refspec: fda737ec0cc1d2a5217548a560074a8e4d5ec580
    path: layers/meta-openembedded
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-filesystems:
      meta-webserver:

