header:
  version: 12

repos:
  poky:
    url: https://git.yoctoproject.org/git/poky
    refspec: scarthgap-5.0.6
    path: layers/poky
    layers:
      meta:
      meta-poky:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    refspec: dda0d53326017d6758ec6bdfdaf2f484c089d13f
    path: layers/meta-openembedded
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-filesystems:
      meta-webserver:

